/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    ARow: typeof import('ant-design-vue/es')['Row']
    ArrowRightOutlined: typeof import('@ant-design/icons-vue')['ArrowRightOutlined']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    BuildTwoTone: typeof import('@ant-design/icons-vue')['BuildTwoTone']
    BulbTwoTone: typeof import('@ant-design/icons-vue')['BulbTwoTone']
    CarryOutTwoTone: typeof import('@ant-design/icons-vue')['CarryOutTwoTone']
    CheckOutlined: typeof import('@ant-design/icons-vue')['CheckOutlined']
    CloseOutlined: typeof import('@ant-design/icons-vue')['CloseOutlined']
    CoffeeOutlined: typeof import('@ant-design/icons-vue')['CoffeeOutlined']
    ColumnHeightOutlined: typeof import('@ant-design/icons-vue')['ColumnHeightOutlined']
    DeleteOutlined: typeof import('@ant-design/icons-vue')['DeleteOutlined']
    ExclamationCircleTwoTone: typeof import('@ant-design/icons-vue')['ExclamationCircleTwoTone']
    MessageTwoTone: typeof import('@ant-design/icons-vue')['MessageTwoTone']
    PlusCircleOutlined: typeof import('@ant-design/icons-vue')['PlusCircleOutlined']
    PushpinTwoTone: typeof import('@ant-design/icons-vue')['PushpinTwoTone']
    ShareAltOutlined: typeof import('@ant-design/icons-vue')['ShareAltOutlined']
    VerticalAlignMiddleOutlined: typeof import('@ant-design/icons-vue')['VerticalAlignMiddleOutlined']
  }
}
